### ISSUE TITLE
Auto-refresh causes jumping comments

### ISSUE THREAD

**Issue by justaaron123** [julianeskin/predictit-enhancer#8] opened 2016-04-14 02:49 UTC
When auto-refresh is enabled, the comments periodically jump, like in this animation (wait for it…)

![jumping](https://cloud.githubusercontent.com/assets/18332389/14515646/90d5b67e-01c1-11e6-8375-0c968bf99e03.gif)

**Comment by julianeskin** [comment] 2016-04-14 03:05
Hard to fix, since the auto-refresh just triggers the built-in manual refresh code. The comments jump when you manually refresh too, except you wouldn't normally be looking at the comments when you did that.

**Comment by curmil** [comment] 2016-04-14 03:09
Maybe I can make the box not resize or wrap it in a container with a set height. Might be an easy fix then.

**Comment by justaaron123** [comment] 2016-04-14 05:16
Yeah, seems like we could:

- At refresh time, inspect the height
- Override the height of the div
- Refresh
- After refresh, remove the height restriction

Alternatively, we could try to hit [the `GetContractListAjax` endpoint](https://www.predictit.org/Home/GetContractListAjax?marketId=2032) manually, then swap out the HTML after it's loaded. That would have the added benefits of removing the flickering effect and the spinning wheel.

**Comment by julianeskin** [comment] 2016-04-15 00:44
They are coming down hard against us accessing any real data, so I don't think we can do what you suggest. We're going to have to get rid of the share value popups too, unfortunately. 

**Comment by getaaron** [comment] 2016-04-15 04:16
That's my favorite feature ☹️…

**Comment by curmil** [comment] 2016-04-17 04:09
This has been fixed in the pending pull request commits.

**Comment by curmil** [comment] 2016-04-17 04:19
@justaaron123 The way I implemented is pretty much the same as your first suggestion. Your second suggestion is the way I would have preferred to do it but the spinner logic is in the functions that handle the ajax requests for the contracts. I could reproduce the ajax requests and remove the spinner logic but they don't want us handling their data in the code, so it's just triggering the click instead.

**Closed** 2016-04-21 13:15 UTC
